mlx_data_path = "data/"
godec_data_path = "godec_data/"
godec_pics_path = "godec_pics/"
godec_gifs_path = "godec_gifs/"
bs_pics_path = "bs_pics/"
bs_results_path = "bs_results/"
bg_subtraction_pics_path = "bg_subtract_pics/"
bg_subtraction_gifs_path = "bg_subtract_gifs/"